# =================================================================================================
# Global hotkeys (cannot conflict with other hotkeys)
confirm = ['enter', 'right', 'l']
quit = ['esc']
# movement
list_up = ['up']
list_down = ['down']
page_up = ['pgup']
page_down = ['pgdown']
# file panel control
create_new_file_panel = ['n', '']
close_file_panel = ['q']
next_file_panel = ['shift+right']
previous_file_panel = ['shift+left']
toggle_file_preview_panel = ['f']
open_sort_options_menu = ['o']
toggle_reverse_sort = ['R']
# change focus
focus_on_process_bar = ['ctrl+p']
focus_on_sidebar = ['s']
focus_on_metadata = ['m']
# create file/directory and rename
file_panel_item_create = ['c']
file_panel_item_rename = ['r']
# file operations
copy_items = ['y']
cut_items = ['x']
paste_items = ['p']
delete_items = ['d']
# compress and extract
extract_file = ['ctrl+e']
compress_file = ['ctrl+a']
# editor
open_file_with_editor = ['e']
open_current_directory_with_editor = ['E']
# other
pinned_directory = ['P']
toggle_dot_file = ['.']
change_panel_mode = ['v']
open_help_menu = ['?']
open_command_line = [':']
copy_path = ['Y']
copy_present_working_directory = ['ctrl+d']
toggle_footer = ['F']
# =================================================================================================
# Typing hotkeys (can conflict with all hotkeys)
confirm_typing = ['enter']
cancel_typing = ['esc']
# =================================================================================================
# Normal mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
parent_directory = ['left']
search_bar = ['/', '']
# =================================================================================================
# Select mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
file_panel_select_mode_items_select_down = ['shift+down']
file_panel_select_mode_items_select_up = ['shift+up']
file_panel_select_all_items = ['A']
