version: 2
log-file: '/tmp/efm.log'
root-markers:
  - .git/
lint-debounce: 1s
tools:
  # gitcommit-gitlint: &gitcommit-gitlint
  #   lint-command: 'gitlint'
  #   lint-stdin: true
  #   lint-formats:
  #     - '%l: %m: "%r"'
  #     - '%l: %m'

  prettierd: &prettierd
    format-command: >
      prettierd ${INPUT} ${--range-start=charStart} ${--range-end=charEnd} ${--tab-width=tabSize}
    format-stdin: true
    root-markers:
      - .prettierrc
      - .prettierrc.json
      - .prettierrc.js
      - .prettierrc.yml
      - .prettierrc.yaml
      - .prettierrc.json5
      - .prettierrc.mjs
      - .prettierrc.cjs
      - .prettierrc.toml

  eslint_d: &eslint_d
    lint-command: >
      eslint_d --stdin --stdin-filename ${INPUT} -f json | jaq -c '.[]|.filePath as $file|.messages[]|[$file,["n","w","e"][.severity],.line//0,.endLine//0,.column//0,.endColumn//0,.message]'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - '["%f","%t",%l,%e,%c,%k,"%m"]'

languages:
  css:
    - <<: *prettierd

  # gitcommit:
  #   - <<: *gitcommit-gitlint

  html:
    - <<: *prettierd

  javascript:
    - <<: *prettierd
    - <<: *eslint_d

  typescript: 
    - <<: *prettierd
    - <<: *eslint_d

  typescriptreact: 
    - <<: *prettierd
    - <<: *eslint_d

  tsx: 
    - <<: *prettierd
    - <<: *eslint_d

  jsx: 
    - <<: *prettierd
    - <<: *eslint_d

  yaml:
    - <<: *prettierd

  json: 
    - <<: *prettierd
