[ids]
0001:0001:a38e6885
0001:0001:70533846

[global]
chord_timeout = 50

[main]
, = ,
. = .
/ = ?
[ = [
] = ]
b = b
b = b
c = d
d = s
e = f
f = t
g = g
h = m
i = u
j = n
k = e
l = i
m = h
n = k
o = y
p = '
q = q
r = p
s = r
t = b
u = l
v = v
w = w
x = c
y = j
z = x
leftshift = z
102nd = z

a = lettermod(control, a, 15, 200)
semicolon = lettermod(control, o, 15, 200)

apostrophe = layer(meta)
space = overload(shift, space)
tab = esc
capslock = layer(meta)
rightalt = layer(nav)
leftalt = layer(sym)
rightcontrol = layer(meta)

i+o = backspace
k+l = enter
j+l = rightbrace
j+k = )

w+e = esc
s+d = tab
s+f = leftbrace
d+f = (

[shift:S]
comma = ;
dot = :
/ = !
d+f = <
j+k = >

[nav]
j = left
k = down
l = right
i = up
u = home
o = end
y = pageup
h = pagedown
f = layer(control)
d = layer(alt)
s = layer(meta)

[sym]
enter = =
k+l = =
r+t = &
u+i = |
rightshift = =
rightalt = .
space = 0
m = 1
, = 2
. = 3
j = 4
k = 5
l = 6
u = 7
i = 8
o = 9
h = +
; = -
n = *
/ = /
p = `
y = ^
' = `

a = _
s = @
d = #
f = $
g = %

w = (
e = )
z = [
x = ]
c = {
v = }
r = &
t = |

102nd = \
leftshift = \
q = ~
